version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: finapp-dev-postgres
    restart: always
    environment:
      POSTGRES_USER: dbFinappUser
      POSTGRES_PASSWORD: devpassword123
      POSTGRES_DB: finappDb
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
